services:

  build:
    image: klakegg/hugo:0.88.0-ext-alpine
    command: build
    volumes:
      - "${PWD}/src:/src"

  serve:
    image: klakegg/hugo:0.88.0-ext-alpine
    command: server -vv
    volumes:
      - "${PWD}/src:/src"
    ports:
      - 1313:1313
    stdin_open: true
    tty: true